dataset:
  repo_id: repo_kai0
  root: Datasets/example/top_long_merged

policy:
  type: kai0
  device: cuda
  push_to_hub: false
  action_dim: 12
  action_horizon: 50
  vision_backbone: paligemma_2b

output_dir: outputs/train/kai0_lehome_run_03
batch_size: 8
steps: 30000
save_freq: 5000
log_freq: 100

wandb:
  enable: false
  project: lehome_kai0
